version: 0.2

env:
  secrets-manager:
    DOCKER_HUB_USERNAME: DockerHubCredentials:DockerHubUsername
    DOCKER_HUB_SECRET: DockerHubCredentials:DockerHubSecret

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: openjdk11
      docker: latest
    commands:
      - pip3 install aws-sam-cli
      - echo "Check docker is running"
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Compile in ontology in multiple formats"
      - |
        jena_version=4.3.1
        wget https://repo1.maven.org/maven2/org/apache/jena/apache-jena/${jena_version}/apache-jena-${jena_version}.tar.gz
        tar xzvf apache-jena-${jena_version}.tar.gz
        export JENA_HOME=apache-jena-${jena_version}
        export PATH=$PATH:$JENA_HOME/bin
        mkdir -p lambda/src/public
        for file in ontology/*.ttl
        do
          file_no_path=$(basename -- "$file")
          filename="${file_no_path%.*}"
          apache-jena-${jena_version}/bin/riot --output=NT $file > ontology-service/src/main/resources/$filename.nt
          apache-jena-${jena_version}/bin/riot --output=TURTLE $file > ontology-service/src/main/resources/$filename.ttl
          apache-jena-${jena_version}/bin/riot --output=RDFXML $file > ontology-service/src/main/resources/$filename.rdf
          apache-jena-${jena_version}/bin/riot --output=JSONLD $file > ontology-service/src/main/resources/$filename.jsonld
        done
      - echo "Build native image"
      - cd ontology-service
      - ./gradlew buildNativeLambda
  build:
      on-failure: ABORT
      commands:
        - cd ..
        - sam build
        - sam package --s3-bucket $S3_BUCKET --output-template-file packaged_raw.yaml
  post_build:
    on-failure: ABORT
    commands:
      # Use timestamp to force update of ApiGatewayCreateDeploymentCustomResource
      - BUILD_TIMESTAMP=$(date '+%s')
      - envsubst '${BUILD_TIMESTAMP}' < packaged_raw.yaml > packaged.yaml
artifacts:
  files:
    - packaged.yaml
