AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: NVA Ontology service


Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Parameters:
  ApiDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Custom API to connect this lambda to
    Default: /NVA/ApiDomain
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in ApiDomain
    Default: ontology

Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  OntologyApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: docs/ontology-service.yaml
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL

  OntologyBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref ApiDomain
      BasePath: !Ref CustomDomainBasePath
      RestApiId: !Ref OntologyApi
      Stage: !Ref OntologyApi.Stage

  OntologyService:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 5
      Handler: Provided
      Runtime: provided
      MemorySize: 512
      Description: Ontology service
      CodeUri: ontology-service/build/libs/ontology-service-0.1-lambda.zip
      Role: !GetAtt OntologyExecutionRole.Arn
      Environment:
        Variables:
          DOMAIN: !Sub ApiDomain
          BASEPATH: !Ref CustomDomainBasePath
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: get
            RestApiId: !Ref OntologyApi

  OntologyExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  DefaultLambdaPermissions:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub DefaultLambdaPermissions-${AWS::StackName}
      Roles:
        - !Ref OntologyExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - lambda:InvokeFunction
            Resource: "*"
