# Transforms turtle in ontology directory to required formats, placing result in public directory

name: Ontology transformation

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install Apache Jena
        run: |
          wget https://dlcdn.apache.org/jena/binaries/apache-jena-4.2.0.tar.gz
          tar xzvf apache-jena-4.2.0.tar.gz
          export JENA_HOME=apache-jena-4.2.0
          export PATH=$PATH:$JENA_HOME/bin

      - name: Transform ontologies
        run: |
          mkdir public
          apache-jena-4.2.0/bin/riot --output=NT ontology/example.ttl > public/output.nt
          apache-jena-4.2.0/bin/riot --output=TURTLE ontology/example.ttl > public/output.ttl
          apache-jena-4.2.0/bin/riot --output=RDFXML ontology/example.ttl > public/output.rdf
          apache-jena-4.2.0/bin/riot --output=JSONLD ontology/example.ttl > public/output.json
          ls public