# Transforms turtle in ontology directory to required formats, placing result in public directory

name: Ontology transformation

on: [push,pull_request]

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install Apache Jena
        run: |
          wget https://dlcdn.apache.org/jena/binaries/apache-jena-4.2.0.tar.gz
          tar xzvf apache-jena-4.2.0.tar.gz
          export JENA_HOME=apache-jena-4.2.0
          export PATH=$PATH:$JENA_HOME/bin

      - name: Transform ontologies
        run: |
          mkdir -p lambda/src/public
          for file in ontology/*.ttl
          do
            file_no_path=$(basename -- "$file")
            filename="${file_no_path%.*}"
            apache-jena-4.2.0/bin/riot --output=NT $file > lambda/src/public/$filename.nt
            apache-jena-4.2.0/bin/riot --output=TURTLE $file > lambda/src/public/$filename.ttl
            apache-jena-4.2.0/bin/riot --output=RDFXML $file > lambda/src/public/$filename.rdf
            apache-jena-4.2.0/bin/riot --output=JSONLD $file > lambda/src/public/$filename.json
          done

      - name: Setup node
        uses: volta-cli/action@v1

      - name: Test node
        run: cd lambda && npm ci && npm run coverage
